# Generated by Django 5.1.4 on 2025-01-21 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='EndUserProfile',
        ),
        migrations.AlterModelOptions(
            name='enduserprofile',
            options={'verbose_name': 'End User Profile', 'verbose_name_plural': 'End User Profiles'},
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('ENDUSER', 'EndUser')], default='STAFF', max_length=50, verbose_name='User Type'),
        ),
        migrations.CreateModel(
            name='StaffUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
    ]
